### ISSUE TITLE
error 404 device Pin

### ISSUE THREAD

**Issue by floflogreco** [geertmeersman/nexxtmove#55]
Hello, 

First of all thank you very much for this awesome integration would never have waited for a proper integration from powerdale.

I installed the integration via HACS and added in HA with my user and password but now I am having this error when the integration is trying to get the device pin. have you already had this issue before?

thanks a lot for your support,

Florian

`2023-07-18 08:40:52.423 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|login|start]

2023-07-18 08:40:52.424 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] 
[NexxtmoveClient|login|authenticate] Calling POST https://nexxtmove.me/b2bev-app-service/api/user/authenticate with {'username': 'hidden', 'password': 'hidden'}

2023-07-18 08:40:52.569 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] 

[NexxtmoveClient|login|authenticate] http status code = 200 (expecting 200)

2023-07-18 08:40:52.569 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] Setting Token eyJwcmluY2lwYWwiOiJGbG9yaWFuLmdyZWNvMTdAZ21haWwuY29tIiwidHlwIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJpc3MiOiJiZS9uZXh4dG1vdmUiLCJleHAiOjE2OTIyNTQ0NTIsImlhdCI6MTY4OTY2MjQ1Mn0.yy4rGR-aiplHEoL84GTJySeA2r9izfANAAZo-lM-Fj7b1bbWDlBtVdnWSAYUe5gjwR4md345-qPHNhzY2EqSeA

2023-07-18 08:40:52.570 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|company] Fetching company info from Nexxtmove

2023-07-18 08:40:52.570 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|company] Calling GET https://nexxtmove.me/b2bev-app-service/api/company

2023-07-18 08:40:52.604 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|company] http status code = 200 (expecting 200)

2023-07-18 08:40:52.605 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|work_buildings] Fetching work buildings from Nexxtmove

2023-07-18 08:40:52.605 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|work_buildings] Calling GET https://nexxtmove.me/b2bev-app-service/api/building/list/work?maxRows=20&offset=0

2023-07-18 08:40:52.637 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|work_buildings] http status code = 200 (expecting 200)

2023-07-18 08:40:52.637 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|charge_latest] Fetching charges from Nexxtmove

2023-07-18 08:40:52.638 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|charge_latest] Calling GET https://nexxtmove.me/b2bev-app-service/api/charge/latest?maxRows=200&offset=0

2023-07-18 08:40:52.689 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|charge_latest] http status code = 200 (expecting 200)

2023-07-18 08:40:52.690 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|consumption] Fetching consumption from Nexxtmove

2023-07-18 08:40:52.690 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|consumption] Calling GET https://nexxtmove.me/b2bev-app-service/api/charge/consumption

2023-07-18 08:40:52.720 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|consumption] http status code = 200 (expecting 200)

2023-07-18 08:40:52.721 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|charges] Fetching charges from Nexxtmove

2023-07-18 08:40:52.721 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|charges] Calling GET https://nexxtmove.me/b2bev-app-service/api/charge/current?maxRows=100&offset=0
2023-07-18 08:40:52.764 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|charges] http status code = 200 (expecting 200)

2023-07-18 08:40:52.765 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|residential_buildings] Fetching residential buildings from Nexxtmove

2023-07-18 08:40:52.765 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|residential_buildings] Calling GET https://nexxtmove.me/b2bev-app-service/api/building/residential?maxRows=20&offset=0

2023-07-18 08:40:52.794 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|residential_buildings] http status code = 200 (expecting 200)

2023-07-18 08:40:52.794 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|device_list] Fetching device list from Nexxtmove

2023-07-18 08:40:52.794 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|device_list] Calling GET https://nexxtmove.me/b2bev-app-service/api/device/list

2023-07-18 08:40:52.836 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|device_list] http status code = 200 (expecting 200)

2023-07-18 08:40:52.837 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|charging_device_graph] Fetching charging graph data from Nexxtmove

2023-07-18 08:40:52.837 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|charging_device_graph] Calling GET https://nexxtmove.me/b2bev-app-service/api/graph/graph/260396?startDate=20220101&endDate=20230718

2023-07-18 08:40:52.886 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|charging_device_graph] http status code = 200 (expecting 200)

2023-07-18 08:40:52.889 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|charging_device_graph] Fetching charging graph data from Nexxtmove

2023-07-18 08:40:52.890 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|charging_device_graph] Calling GET https://nexxtmove.me/b2bev-app-service/api/graph/graph/260396?startDate=20230619&endDate=20230718

2023-07-18 08:40:52.927 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|charging_device_graph] http status code = 200 (expecting 200)

2023-07-18 08:40:52.933 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|device_pin] Fetching device pin from Nexxtmove

2023-07-18 08:40:52.935 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|device_pin] Calling GET https://nexxtmove.me/b2bev-app-service/api/device/260396/pin

2023-07-18 08:40:52.962 DEBUG (SyncWorker_5) [custom_components.nexxtmove.utils] [NexxtmoveClient|device_pin] http status code = 404 (expecting 200)

2023-07-18 08:40:52.964 DEBUG (MainThread) [custom_components.nexxtmove.const] Finished fetching nexxtmove data in 0.542 seconds (success: False)`

**Comment by geertmeersman** [comment]
Hi, no but perhaps you don't have a device pin in your setup :-)
I'll put the check  "optional"

**Comment by geertmeersman** [comment]
Done: https://github.com/geertmeersman/nexxtmove/releases/tag/v0.7.0

**Comment by floflogreco** [comment]
Thanks for your quick support!
I am still having an issue, I think it’s because I own one charging station of the 16 powerdale cluster ( residential apartment) and it’s trying to get the device event for the cluster for which I probably don’t have the rights.

2023-07-18 09:26:05.487 DEBUG (SyncWorker_2) [custom_components.nexxtmove.utils] [NexxtmoveClient|device_pin] Fetching device pin from Nexxtmove
2023-07-18 09:26:05.488 DEBUG (SyncWorker_2) [custom_components.nexxtmove.utils] [NexxtmoveClient|device_pin] Calling GET https://nexxtmove.me/b2bev-app-service/api/device/260396/pin
2023-07-18 09:26:05.539 DEBUG (SyncWorker_2) [custom_components.nexxtmove.utils] [NexxtmoveClient|device_pin] http status code = 404 (expecting 200)
2023-07-18 09:26:05.539 DEBUG (SyncWorker_2) [custom_components.nexxtmove.utils] [NexxtmoveClient|device_events] Fetching device events from Nexxtmove
2023-07-18 09:26:05.539 DEBUG (SyncWorker_2) [custom_components.nexxtmove.utils] [NexxtmoveClient|device_events] Calling GET https://nexxtmove.me/b2bev-app-service/api/device/260396/events
2023-07-18 09:26:05.568 DEBUG (SyncWorker_2) [custom_components.nexxtmove.utils] [NexxtmoveClient|device_events] http status code = 404 (expecting 200)
2023-07-18 09:26:05.570 DEBUG (MainThread) [custom_components.nexxtmove.const] Finished fetching nexxtmove data in 0.622 seconds (success: False)

**Comment by floflogreco** [comment]
It worked, you’re awesome man!

buying you a Duvel right now!
